/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mynotepad;

import javax.swing.*;
import java.io.*;

/**
 *
 * @author user
 */
public class NotePad extends javax.swing.JFrame {
	
	BufferedReader br;
	PrintWriter pw;

    /**
     * Creates new form NotePad
     */
    public NotePad() {
    	super("::NotePad v1.1::");
        initComponents();
        tfDir.setText("C:/MyJava");//디렉토리창의 기본값
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btNew = new javax.swing.JButton();
        btOpen = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btHelp = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        tfDir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.png"))); // NOI18N
        btNew.setFocusable(false);
        btNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btNew);

        btOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open.png"))); // NOI18N
        btOpen.setFocusable(false);
        btOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenActionPerformed(evt);
            }
        });
        jToolBar1.add(btOpen);

        btSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btSave.setFocusable(false);
        btSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btSave);
        jToolBar1.add(filler1);

        btHelp.setText("Help");
        btHelp.setFocusable(false);
        btHelp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btHelp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHelpActionPerformed(evt);
            }
        });
        jToolBar1.add(btHelp);

        jSplitPane1.setDividerLocation(170);
        jSplitPane1.setDividerSize(7);
        jSplitPane1.setOneTouchExpandable(true);

        tfDir.setBorder(javax.swing.BorderFactory.createTitledBorder("::Directory::"));
        tfDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDirActionPerformed(evt);
            }
        });

        list.setBorder(javax.swing.BorderFactory.createTitledBorder("::List:::"));
        list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfDir, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tfDir, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        ta.setColumns(20);
        ta.setRows(5);
        ta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 3, true));
        jScrollPane2.setViewportView(ta);

        lb.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lb.setForeground(new java.awt.Color(102, 102, 102));
        lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb.setText("No Image");
        jScrollPane3.setViewportView(lb);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void showMsg(String msg) {
       JOptionPane.showMessageDialog(this, msg);
    }

    private void btNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewActionPerformed
       ta.setText("");
    }//GEN-LAST:event_btNewActionPerformed

    private void btOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenActionPerformed
       int n=jfc.showOpenDialog(this);
       if(n==JFileChooser.APPROVE_OPTION) {
    	   File file=jfc.getSelectedFile();
       		if(file==null)return;
       		String path=file.getAbsolutePath();
       		readFile(path);
       }
    }//GEN-LAST:event_btOpenActionPerformed
    
    JFileChooser jfc=new JFileChooser("C:/MyJava");//파일선택 다이얼로그
    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//파일 저장을 위해 창을 띄워주는 것
        int n=jfc.showSaveDialog(this);//파일 저장을 위해 창을 띄워주는 것
       // setTitle("n="+n);//저장일때 0 취소일 때 1을 반환하는걸 확인하기위해
        if(n==JFileChooser.APPROVE_OPTION) {
        	//저장할 파일명 얻기==>절대경로 얻기
        	File file=jfc.getSelectedFile();
        	System.out.println(file);
        	if(file==null)return;
        	String path=file.getAbsolutePath();
        	setTitle(path);
        	
        	//저장할 내용 얻기=> ta에서 얻어오기
        	String contents =ta.getText();
        	
        	//해당 파일이 존재하는지 여부를 판단해서 존재하면 "덮어쓸까요?"
        	//존재하지 않으면 그냥 저장
        	if(file.exists()) {
        		//이미 존재하는 파일이라면 확인
        		int n2=JOptionPane.showConfirmDialog(ta,"이미 존재하는 파일입니다. 엎어쓸까요?");
        		if(n2==JOptionPane.YES_OPTION) {
        			saveFile(path,contents);
        		}
        	}else {
        		saveFile(path,contents);
        	}
        }
        
    }//----------------------------------------------------------------------------------

    private void btHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHelpActionPerformed
       showMsg("Notepad v1.1\n작성일:2021-06-17\n작성자:박지민");
    }//GEN-LAST:event_btHelpActionPerformed

    public void checkDir(String str) {//[1]해당 디렉토리에 목록받아와서 리스트에 뿌려주기기능
    	// int indexOf(Char|String)
    	//특정 문자나 문자열이 위치한 인덱스 번호를 반환한다.
    	//해당 문자/문자열이 없으면 -1을 반환한다.
    	int i=str.indexOf('/');//슬레시를 가지고 있는
    	int i2=str.indexOf("\\");//역슬래시를 가지고 인는지
    	System.out.println(i+"/"+i2);
    	
    	//2. 유효성 체크(null,빈문자열)
    	if(str==null||str.trim().isEmpty()) {
    		showMsg("디렉토리명을 입력하세요");
    		return;
    	}
    	//3. 입력한 값이 디렉토리인지 여부 판단
    	File dir=new File(str);
    	if(!dir.isDirectory()|| i==-1&&i2==-1) {//디렉토리가 아니거나 i가 -1이거나 i2가 -1이 아니라면
    		showMsg("디렉토리가 아닙니다. 이덹토리명을 입력하세요");
    		tfDir.setText("");
    		return;
    	}
    	//4. 디렉토리라면 해당 디렉토리의 파일목록 가져와서 JList에 출력하기
    	String[] fList=dir.list();//데이터를 의미 ==> Model이 갖는다.
    	//Jlist(View) ==> DefaultListModel
    	if(fList!=null) {
    		DefaultListModel<String> model=new DefaultListModel();
    		for(String fname: fList) {
    			model.addElement(fname);
    		}
    		//뷰와 모델을 연결
    		list.setModel(model);
    	}
    	
    }
    
    private void tfDirActionPerformed(java.awt.event.ActionEvent evt) {//디렉토리 명을 입력받고 예외를 처리하는 과정
    	//1. tfDir에 입력한 값 받아오기
    	String str=tfDir.getText();
    	
    	checkDir(str);//복잡하니까 위로 옮겨서 불러오는 것
    	
    	File dir=new File(str);	
    }//-----------------------------------------------------------------

    private void listValueChanged(javax.swing.event.ListSelectionEvent evt) {//[2]리스트에서 텍스트 파일 선택시 텍스트 에어리어로 이동하게
    		boolean b=evt.getValueIsAdjusting();//마우스 클릭하면 두번먹는데 한번만 먹게 하는 코드
    		//System.out.println("b:"+b);
    		if(b) {
    			//1. list에서 선택한 몰록값 가져오기
    			String str=list.getSelectedValue();
    		
    			//2. 선택한 파일의 확장자가.jpg, .png.gif파일이라면
    			//=>해당 이미지를 lb에 보여준다.
    			//boolean endsWith(String str)(str내용)로 끝나면 true값으로 보내준다
    			String str2=str.toLowerCase();
    			String path=tfDir.getText()+"/"+str;//tfDir.getText()+"/"+str이렇게하면 절대경로
    			
    			if(str2.endsWith(".jpg")||str2.endsWith(".png")||str2.endsWith(".gif")) {
    				
    						setTitle(path);
    						previewImage(path);
    			
    			}
    	
    			//3. 파일 확장자가 .txt .java .html이라면 해당 파일의
    			//절대경로를 구해서 파일 입력스트림과 연결하여  읽은 두에
    			//읽은 내용을 텍스트에어리어에 출력한다.
    			if(str2.endsWith(".txt")||str2.endsWith(".java")||str2.endsWith(".html")) {
    				setTitle(path);
    				readFile(path);
    			}
    		}
       
    }//-------------------------------------
    
   public void readFile(String path) {//[2]리스트에서 파일 선택하면 파일 읽어주기
	   try {
		 //path와==>노드스트림 연결 ==> BufferedReader로 필터링
		   //br=new BufferedReader(new FileReader(path));
		   br=new BufferedReader(new InputStreamReader(new FileInputStream(path),"EUC-kR"));//인코딩으로 브릿지스트림을 쓰면 장점이 한글 깨지는걸 막을 수 있다.
		   String line="";
		   ta.setText("");
		   
		   //반복문 돌면서 line단위로 읽어서 ta에 append
		   while((line=br.readLine())!=null) {
			   ta.append(line+"\r\n");
		   }
		   br.close();
		   
	} catch (IOException e) {
		showMsg(e.getMessage());
	}
	   
   }//-------------------------------------

   public void saveFile(String path,String contents) {//세이브 버튼 누르면 저장되게(path)로 불러와  contents에 저장
	   try {
		pw=new PrintWriter(new FileWriter(path),true);
		pw.println(contents);
		pw.close();
		setTitle(path+"에 저장 완료!!");
	} catch (Exception e) {
		showMsg(e.getMessage());
	}
	   //pw 생성해서 파일과 연결한 뒤에
	   
	   //파일에 쓸 내용 내보내기
	   
	   //스트림 연결 닫기
	   
   }//-------------------------------------------------}
   
    public void previewImage(String path) {
		ImageIcon icon=new ImageIcon(path);
		lb.setIcon(icon);
		lb.setText("");
		
	}

	/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               System.out.println(info.getName());
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotePad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHelp;
    private javax.swing.JButton btNew;
    private javax.swing.JButton btOpen;
    private javax.swing.JButton btSave;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lb;
    private javax.swing.JList<String> list;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField tfDir;
    // End of variables declaration//GEN-END:variables
}